table dim_date
	lineageTag: 0a68dd34-85fa-4d50-b212-054db9205eda

	column date_key
		dataType: int64
		formatString: 0
		lineageTag: d6c956b3-427f-4369-98e6-63b3dc76618f
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0201707d-33db-4bd4-9cf0-81501fed35ec
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 25f9de6f-4200-44cb-81ba-59a401e38c50
			defaultHierarchy: LocalDateTable_3fd3acff-66de-4e95-b7f2-3e01cf0110c2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		formatString: 0
		lineageTag: a581bc5d-b578-40ac-a640-b8da97212039
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 7d8ddb7b-8389-4316-aa32-07ba32825ef5
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: 39cc6244-6946-4a8e-8fbb-fc10298a69f8
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: f6dc5577-5f2a-4850-9737-a9c9e2e28c3b
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column month_start
		dataType: dateTime
		formatString: Long Date
		lineageTag: cb079b6e-f655-4032-b816-cac8924750d6
		summarizeBy: none
		sourceColumn: month_start

		variation Variation
			isDefault
			relationship: 21be90b7-cc89-4140-9c7e-e13ec541245a
			defaultHierarchy: LocalDateTable_797f0920-c63c-4e25-a85f-429614f63289.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column week
		dataType: int64
		formatString: 0
		lineageTag: 97defea2-a1d8-4cf4-a41e-e2b48d8920af
		summarizeBy: sum
		sourceColumn: week

		annotation SummarizationSetBy = Automatic

	column day_of_week
		dataType: int64
		formatString: 0
		lineageTag: 4747d00e-7ffd-4b1d-b46d-dc574a10a04a
		summarizeBy: sum
		sourceColumn: day_of_week

		annotation SummarizationSetBy = Automatic

	column day_name
		dataType: string
		lineageTag: 26249d1a-698c-4e20-9d17-aa0f5d88657d
		summarizeBy: none
		sourceColumn: day_name

		annotation SummarizationSetBy = Automatic

	column 'Is Month End' = ```
			
			IF ( 
			    dim_date[date] = EOMONTH ( dim_date[date], 0 ), 1, 0 )
			```
		formatString: 0
		lineageTag: c8b0196a-a1da-40cc-afed-be46d15ed527
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition dim_date = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\AlexOchokiMogengo\Projects\microfinance\npl_demo_datasets\dim_date.csv"),[Delimiter=",", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"date_key", Int64.Type}, {"date", type date}, {"year", Int64.Type}, {"quarter", Int64.Type}, {"month", Int64.Type}, {"month_name", type text}, {"month_start", type date}, {"week", Int64.Type}, {"day_of_week", Int64.Type}, {"day_name", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

