table dim_branch
	lineageTag: 344c9a9d-c7d0-4911-803a-9702bb08e9ff

	column branch_id
		dataType: int64
		formatString: 0
		lineageTag: d563e6de-2140-4ea6-894b-9977145d79a4
		summarizeBy: none
		sourceColumn: branch_id

		annotation SummarizationSetBy = Automatic

	column branch_name
		dataType: string
		lineageTag: f808a88a-741d-4971-8fff-466db57390ec
		summarizeBy: none
		sourceColumn: branch_name

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 6e156d15-fc03-48a7-a07b-7e43d322e60a
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column urban_rural
		dataType: string
		lineageTag: 2b2faf61-5d58-4b4c-9dfb-f2e18fdc3a10
		summarizeBy: none
		sourceColumn: urban_rural

		annotation SummarizationSetBy = Automatic

	partition dim_branch = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\AlexOchokiMogengo\Projects\microfinance\npl_demo_datasets\dim_branch.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"branch_id", Int64.Type}, {"branch_name", type text}, {"region", type text}, {"urban_rural", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

