table 'Risk Concentration'
	lineageTag: be7b2347-a4c0-4b1f-b4bb-08e150cf6c89

	measure 'NPL Exposure (Selected Snapshot)' = ```
			
			VAR SnapKey = [Snapshot Date Key (Selected or Latest)]
			RETURN
			CALCULATE (
			    [NPL Exposure (Month-End)],
			    KEEPFILTERS ( fact_dpd_snapshot[snapshot_month_end_date_key] = SnapKey )
			)
			
			```
		lineageTag: ab366d52-696c-4c2b-a245-3f975553c9ef

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Portfolio (Selected Snapshot)' =
			
			VAR SnapKey = [Snapshot Date Key (Selected or Latest)]
			RETURN
			CALCULATE (
			    [Gross Loan Portfolio],
			    KEEPFILTERS ( fact_dpd_snapshot[snapshot_month_end_date_key] = SnapKey )
			)
		lineageTag: ad7c1b6e-bddc-492f-a399-301b0ad79138

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'NPL % (Selected Snapshot)' =
			
			DIVIDE ( [NPL Exposure (Selected Snapshot)], [Portfolio (Selected Snapshot)] )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 285e324d-4d6c-4f87-8ca2-f806ea359390

	measure 'PAR90 Amount (Selected Snapshot)' =
			
			[Portfolio (Selected Snapshot)] * [PAR 90 %]
		lineageTag: 90f9aabd-85c2-4570-8843-df9514cd6a82

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'NPL Contribution %' = ```
			
			DIVIDE (
			    [NPL Exposure (Selected Snapshot)],
			    CALCULATE ( 
			        [NPL Exposure (Selected Snapshot)], 
			        ALL ( dim_customer[customer_segment] ) )
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 22e89c94-b243-4b0b-b77e-656b1e4403e7

	measure 'NPL Segment Rank' = ```
			
			RANKX (
			    ALL ( dim_customer[customer_segment]),
			    [NPL Exposure (Selected Snapshot)],
			    ,
			    DESC,
			    Dense
			)
			
			```
		formatString: 0
		lineageTag: 7faa314c-a2dc-4435-b4f3-56712f26f84a

	measure 'NPL Exposure (Top Segments Only)' = ```
			
			VAR TopN_ = 6
			RETURN
			IF (
			    [NPL Segment Rank] <= TopN_,
			    [NPL Exposure (Selected Snapshot)]
			)
			
			```
		lineageTag: c8d44174-c9c5-4003-adc4-acd6bfc14657

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'NPL % Color Band' =
			
			SWITCH (
			    TRUE(),
			    [NPL % (Selected Snapshot)] >= 0.10, 3,
			    [NPL % (Selected Snapshot)] >= 0.05, 2,
			    1
			)
		formatString: 0
		lineageTag: 6bf202a2-a9b3-4228-9acf-1227b94a209b

	column Column
		formatString: 0
		lineageTag: ce85edad-f28d-4eb2-970d-9e50ef5ec9c2
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition 'Risk Concentration' = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = b572d1edcf0f4722be9a199b8c8d0a69

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

